Make compile with MSVC++ 19.29.30151.0
This commit fixes the following compilation errors:
C:\builds\kdevelop\kdevelop\plugins\clang\codecompletion\context.cpp(538):
    error C3493: 'prefixSize' cannot be implicitly captured because no default capture mode has been specified
C:\builds\kdevelop\kdevelop\plugins\clang\codecompletion\context.cpp(542):
    error C2064: term does not evaluate to a function taking 1 arguments
<4 more C2064 errors close by>

The same MSVC bug was similarly worked around in
1952386c834a0aa067be5992f9c48a5c49e0036f. Both commits should be
reverted once building KDevelop with Visual Studio 2019 is no longer
supported.