Replace QVariant::setValue() with QVariant::fromValue()
Explicitly specifying a value type for QVariant::setValue() does not
compile against Qt 6, because setValue() takes a forwarding reference
rather than a const reference as in Qt 5. The relevant part of the
ensuing compilation error:
/usr/include/qt6/QtCore/qvariant.h:492:10: note:   template argument deduction/substitution failed:
quickopenmodel.cpp:317:30: note:   cannot convert ‘w’ (type ‘QWidget*’) to type ‘QWidget*&&’

Don't specify the type to make compile against Qt 6. Simplify with
QVariant::fromValue().