Fix compilation error with MSVC 2017:
Undefined reference to "bool SetNodeDataRequest::equals(const SetNodeData* item) const;"

(cherry picked from commit fdaf9758fb4dbca2ca985c7cb3bf3599655764dc)