Fix MSVC build
Yet again, I have *no* clue why/when this worked before and even why it
doesn't work at the moment. Compiles fine for other initializer-list
uses.

Error:
z:\kderoot\download\git\kdevplatform\interfaces\iplugincontroller.h(125)
: error C2440: 'default argument' : cannot convert from
'initializer-list' to 'const QVariantMap &'
        Reason: cannot convert from 'initializer-list' to 'const
QVariantMap'
        No constructor could take the source type, or constructor
overload resolution was ambiguous