Explicitly cast QStringBuilder to QByteArray
The type of the second parameter to qputenv() changed from QByteArray
to QByteArrayView in Qt 6.5. QStringBuilder is not implicitly
convertible to QByteArrayView, which causes a compilation error while
building against Qt 6.5 or later:
standarddocumentationview.cpp:104:65: error: could not convert ‘operator+<const QByteArray&, const char (&)[35]>(chromiumFlags, " --disable-in-process-stack-traces")’ from ‘QStringBuilder<const QByteArray&, const char (&)[35]>’ to ‘QByteArrayView’
  104 |             qputenv("QTWEBENGINE_CHROMIUM_FLAGS", chromiumFlags + " --disable-in-process-stack-traces");
      |                                                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                 |
      |                                                                 QStringBuilder<const QByteArray&, const char (&)[35]>