tests: separate testhelpermacros.h from testhelpers.h
Some tests need only the macros. Also including <tests/testhelpers.h> in
test_gdbprinters.cpp causes compilation errors like
kdevelop/kdevplatform/tests/testhelpers.h:10:10: fatal error: testsexport.h: No such file or directory
   10 | #include "testsexport.h"
      |          ^~~~~~~~~~~~~~~
and, once that is fixed by replacing "testsexport.h" with
<tests/testsexport.h>,
kdevelop/kdevplatform/serialization/referencecounting.h:11:10: fatal error: serializationexport.h: No such file or directory
   11 | #include "serializationexport.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~