Explicitly cast (Modifier|Key) to QKeySequence
For some reason, operator|(Qt::Modifier, Qt::Key) returns unsigned int
in Qt 5 but QIncompatibleFlag in Qt 6. unsigned int is but
QIncompatibleFlag is not implicitly convertible to QKeySequence. This
causes the following compilation error while building against Qt 6:
applychangeswidget.cpp:67:36: error: cannot convert ‘QIncompatibleFlag’ to ‘const QKeySequence&’
   67 |     okButton->setShortcut(Qt::CTRL | Qt::Key_Return);
      |                           ~~~~~~~~~^~~~~~~~~~~~~~~~
      |                                    |
      |                                    QIncompatibleFlag