appimage: Bump to KDE Apps 16.12.3
Attempt to fix compilation problem in konsole:
/kf5/konsole/src/Session.cpp:839:9: error: missing binary operator
before token "defined"
 #if not defined(REMOVE_SENDTEXT_RUNCOMMAND_DBUS_METHODS)
         ^