my FlexLexer.h is in -I/opt/kde4-deps/include but since it was never searched, that -I never got added to the compile line, and thus the FlexLexer.h in /usr/include was found instead:
/Users/ranger/cvs/packages/compile.build/kdevelop/buildtools/managers/qmake/parser/qmake_lexer.cpp: In member function 'virtual int QMake::Lexer::yylex()':
/Users/ranger/cvs/packages/compile.build/kdevelop/buildtools/managers/qmake/parser/qmake_lexer.cpp:955: error: 'yy_buffer_stack' was not declared in this scope

This fixes it by searching for the header and adding appropriately.  :)