Work around weird MSVC2015 bug
While at it, remove unused function parameter

Error:
Z:\kderoot\download\git\kdevplatform\plugins\patchreview\patchhighlighter.cpp
Z:\kderoot\include\QtCore/qpair.h(51): error C2587: 't1': illegal use of
local v
ariable as default parameter
Z:\kderoot\include\QtCore/qpair.h(51): note: see declaration of 't1'
Z:\kderoot\include\QtCore/qpair.h(51): error C2587: 't2': illegal use of
local v
ariable as default parameter
Z:\kderoot\include\QtCore/qpair.h(51): note: see declaration of 't2'