MemoryView: add missing and sort includes
The QActionGroup include is necessary to prevent multiple compilation
errors like the following:
kdevelop/plugins/gdb/memviewdlg.cpp:272:50: error: invalid use of incomplete type ‘class QActionGroup’

Note that Okteta has not been officially ported to KF6 yet, so KDevelop
had not been built with the CMake option KDEV_WITH_MEMVIEW (which
enables compilation of memviewdlg.cpp) enabled for about a year. I have
thrown together a quick and dirty patch to build KDevelop against the
current snapshot of the KF6 Okteta version in order to test MemoryView.
Therefore, the QActionGroup include is probably necessary only with
relatively recently released (about a year ago or less) Qt versions.