Make compile with MSVC++ 19.24
This commit fixes the following compilation errors:
..\kdevplatform\util\environmentprofilelist.cpp(260): error C3493:
  'escapeChar' cannot be implicitly captured because no default capture mode has been specified
..\kdevplatform\util\environmentprofilelist.cpp(260): error C3493:
  'variableStartChar' cannot be implicitly captured because no default capture mode has been specified
..\kdevplatform\util\environmentprofilelist.cpp(273): error C2064:
  term does not evaluate to a function taking 1 arguments
<plus most likely similar errors in kdevplatform/util/kdevstringhandler.cpp>

The Microsoft Solution for the relevant bug report
https://developercommunity.visualstudio.com/content/problem/610504/lambda-fails-to-implicitly-capture-constexpr-value.html
reads: "It had been fixed with /experimental:newLambdaProcessor."

I don't suppose enabling experimental flags when building KDevelop is a
good idea. Let us work this compiler bug around instead: specify the
default capture mode as `=`.