Make EnvironmentInformation[List]Item noncopyable
When a copy assignment operator is deleted, a copy constructor is still
generated. But this generation is deprecated since C++11 => disable it.

Remove the default argument from EnvironmentInformationListItem's
pseudo-copy-constructor and pass the second argument explicitly to fix
the following compilation error after EnvironmentInformationListItem
becomes noncopyable:
kdevplatform/language/duchain/duchain.cpp:560:83: error: call of overloaded ‘EnvironmentInformationListItem(const KDevelop::EnvironmentInformationListItem&)’ is ambiguous