Work-around compile issue in MSVC2017
Issue (excerpt):
```
10:04:49 C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\include\xutility(729): error C2666: 'QTypedArrayData<T>::iterator::operator +': 2 overloads have similar conversions
10:04:49         with
10:04:49         [
10:04:49             T=KDevelop::Path
10:04:49         ]
...
```

(cherry picked from commit 0e6fce2881e9f7ac916332def048567707580cc4)