Doxyfile: make doxygen work correctly, add treeview, search
Replace "lib" with "kdevplatform" in INPUT paths to KDevPlatform
libraries. The resulting list is imperfect, but at least now there are
*some* sources to generate documentation from.

The IMAGE_PATH Doxygen tag is for the \image Doxygen command. The only
image in doc/api - Development.png - was removed in
568951b588c0bca052e62609d33c8616073bc372. So unset the IMAGE_PATH tag.

The files referred to by HTML_HEADER, HTML_FOOTER and HTML_STYLESHEET
tags were removed from doc/api/common/ in
568951b588c0bca052e62609d33c8616073bc372. Unset these tags to fix errors
like the following:
error: tag HTML_HEADER: header file 'doc/api/common/header.html' does not exist

Possible values of the PAPER_TYPE tag are: a4, letter, legal, executive.
Unset the PAPER_TYPE tag to get rid of the following warning:
warning: argument 'a4wide' for option PAPER_TYPE is not a valid enum value
Using the default: a4!

Set the COLLABORATION_GRAPH, INCLUDE_GRAPH and INCLUDED_BY_GRAPH tag
values to NO. When these options are enabled, many .png files are
generated, which increases the size of the generated documentation by
more than a 100 MB. The include graphs are not very useful and a large
collaboration graph can be confusing.

Generate a tree view and a search engine to greatly facilitate
navigation through the documentation.