PrinterForwarder: don't require the display_hint attribute
Prevents the following error:
Python Exception <class 'AttributeError'>: 'QCborSimpleTypePrinter' object has no attribute 'display_hint'