Make compile
clangsignatureassistant.h:40:24: error:
    cannot define or redeclare 'Cursor' here because namespace
    'KDevelop' does not enclose namespace 'KTextEditor'