DefinesModel: replace qMakePair with QPair
Explicit template arguments to qMakePair() cause the following
compilation error with GCC 14.1.1:
definesmodel.cpp:142:57: error: cannot bind rvalue reference of type ‘QString&&’ to lvalue of type ‘const QString’
  142 |          m_defines << qMakePair<QString,QString>( it.key(), it.value() );
      |                                                   ~~~~~~^~
...
/usr/include/qt6/QtCore/qpair.h:19:41: note:   initializing argument 1 of ‘constexpr decltype(auto) qMakePair(T1&&, T2&&) [with T1 = QString; T2 = QString]’
   19 | constexpr decltype(auto) qMakePair(T1 &&value1, T2 &&value2)
      |                                    ~~~~~^~~~~~

An alternative fix is to remove the explicit template arguments and let
qMakePair() deduce them. But the choice does not really matter, because
this code can be both simplified and optimized by leveraging
QKeyValueIterator and QList::assign() given Qt version >= 6.6. The next
commit implements this improvement.