Compile++
Clang 3.4 complains:

.../parsesession.cpp:169:36: error: default
initialization of an object of const type 'const
ClangDiagnosticEvaluator' requires a user-provided default constructor
    const ClangDiagnosticEvaluator evaluator;