clangtidy: boost::string_ref => std::string_view
std::string_view should be at least as efficient as boost::string_ref.
The used interface should and appears to be compatible. From
https://www.boost.org/doc/libs/1_78_0/libs/utility/doc/html/utility/utilities/string_view.html :
Please prefer string_view / basic_string_view over string_ref / basic_string_ref:
...
- Code that uses basic_string_ref should continue to work.

Remove the Boost dependency from kdevclangtidy and thus get rid of the
following linker error with Boost version 1.83:
/usr/include/boost/utility/string_ref.hpp:170:
(.text._ZNK5boost16basic_string_refIcSt11char_traitsIcEE6substrEmm[_ZNK5boost16basic_string_refIcSt11char_traitsIcEE6substrEmm]+0x88):
undefined reference to `boost::throw_exception(std::exception const&, boost::source_location const&)'