Don't rely on implicitness of QChar(int) constructor
Since Qt 6, QChar(int) is explicit unless the macro
QT_IMPLICIT_QCHAR_CONSTRUCTION is defined. The documentation recommends
using explicit conversions and/or QLatin1Char rather than define the
macro. Explicitly cast to QLatin1Char in all 3 places touched by this
commit, because only ASCII character codes are converted.

This fixes the following compilation error while building against Qt 6:
miparser.cpp:346:29: error: conversion from ‘int’ to ‘QChar’ is ambiguous
  346 |             message2.append(translated);
      |                             ^~~~~~~~~~