test_duchain-clang: add missing include into parsed test file
TestDUChain::testGccCompatibility() consistently fails on my GNU/Linux
system with the following (abbreviated) output:
/usr/include/c++/15.1.1/x86_64-pc-linux-gnu/bits/c++config.h:889:25: error: invalid suffix 'bf16' on floating constant
/tmp/test_duchain-clang-JCHwat/testfile_ecpBHa.cpp:5:46: error: use of undeclared identifier 'uint32_t'
QDEBUG : kdevelop.plugins.clang: failed to find declaration for base specifier: decltype(__detail::__or_fn<_Bn...>(0))
...
QDEBUG : kdevelop.plugins.clang: failed to find declaration for base specifier: is_convertible<_Yp *, _Tp *>::type
QDEBUG : "/tmp/test_duchain-clang-JCHwat/testfile_ecpBHa.cpp" QList("Error: Use of undeclared identifier 'uint32_t' in /tmp/test_duchain-clang-JCHwat/testfile_ecpBHa.cpp:[(4,45),(4,53)]: <no explanation> (found by Semantic analysis)" )
FAIL!  : TestDUChain::testGccCompatibility(sized-dealloc) parse error detected
   Loc: [kdevelop/plugins/clang/tests/test_duchain.cpp(2064)]

In contrast, test_duchain-clang consistently passes on the OpenSUSE
Tumbleweed CI servers. The likely reason is that GCC version 14.2.1 is
installed on the CI servers, and the failure probably started appearing
on my system since a recent GCC version upgrade from 14.2.1 to 15.1.1.

The standard library header stdint.h defines `uint32_t` used in the code
of the parsed test file. Insert `#include <stdint.h>` into the test file
in order to eliminate the parse error and consequently the test failure.