Expect failure when parsing c++config.h from GCC with clang
On my system that triggers an error like this:
```
/usr/include/c++/14.1.1/x86_64-pc-linux-gnu/bits/c++config.h:827:25: error: invalid suffix 'bf16' on floating constant
```

We cannot do anything about this, so don't fail the test.

Probably this will resolve itself once clang supports these
C++23 suffixes, see also:
See also: https://en.cppreference.com/w/cpp/types/floating-point