BreakpointWidget: disambiguate QKeySequence constructor overload
This fixes the following GCC compilation error introduced by the parent
commit:
breakpointwidget.cpp:125:69: error: call of overloaded ‘QKeySequence(KeyCombinationIfModifiersAndKeyTypes<Qt::Modifier, Qt::Key>, Qt::Key)’ is ambiguous
  125 |     action->setShortcut(QKeySequence(Qt::CTRL | Qt::Key_B, Qt::Key_C));
      |                                                                     ^
...
/usr/include/qt6/QtGui/qkeysequence.h:123:5: note: candidate: ‘QKeySequence::QKeySequence(QKeyCombination, QKeyCombination, QKeyCombination, QKeyCombination)’
  123 |     QKeySequence(QKeyCombination k1,
      |     ^~~~~~~~~~~~
/usr/include/qt6/QtGui/qkeysequence.h:122:5: note: candidate: ‘QKeySequence::QKeySequence(int, int, int, int)’
  122 |     QKeySequence(int k1, int k2 = 0, int k3 = 0, int k4 = 0);
      |     ^~~~~~~~~~~~