patchreview: Restore libkomparediff2 5.0 support
Failed with:
/usr/include/libkomparediff2/kompare.h:93:32: error: 'QString::QString(const char*)' is private within this context
    QString _localDestination = "",
                                ^~

(cherry picked from commit b03b30c2ffb66ea1a43c5ed550e37da19933cf97)