codemodel: Kill broken testReferenceCounting func
Caused compiler warnings, and didn't even compile when enabled:

/home/kfunk/devel/src/kf5/kdevplatform-production/language/duchain/codemodel.cpp:80:3:
error: invalid use of 'this' outside of a non-static member function
/home/kfunk/devel/src/kf5/kdevplatform-production/language/duchain/codemodel.cpp:82:39:
error: no member named 'hasReferenceCount' in
'KDevelop::IndexedQualifiedIdentifier'