Fix build with Qt 5.9
Fixes for ld error: undefined reference to `bool QTest::qCompare<unsigned long, int>(...)'

(cherry picked from commit bae46276b2ce34c9a59adc8b69bcfacc4b6c186f)