Revert "Select core dialog: stick dialog buttons to bottom"
Fix compilation.

Error:
  debuggers/common/dialogs/selectcoredialog.cpp:38:17: error: no member
named 'binaryFile' in 'Ui::SelectCoreDialog'

CCMAIL: kossebau@kde.org

This reverts commit 12c3bdd5290965173b0a03fe0e16e6ac5b263bb8.